import type { Metadata } from "next";
import "./globals.css";
import React from 'react';
import Icon from './components/Icon_andy';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased font-sans" style={{ backgroundColor: '#112121' }}>
        <nav className="fixed top-0 left-0 right-0 bg-slate-900/50 backdrop-blur-md border-b border-cyan-500/20 p-4 z-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center">
              <div className="flex gap-4">
                <a href="/" className="hover:underline text-gray-900">Home</a>
                <a href="/chat" className="hover:underline text-gray-900">Chat</a>
              </div>
              <div className="hidden sm:flex gap-4">
                <a href="/documents" className="hover:underline text-gray-900">Documents</a>
                <a href="/tax" className="hover:underline text-gray-900">Tax Advisor</a>
              </div>
            </div>
          </div>
        </nav>
        <div className="fixed top-4 left-4 z-50"> {/* Added div for icon positioning */}
          <Icon />
        </div>
        <main className="pt-20 min-h-screen"> {/* Increased top padding to avoid overlap */}
          {children}
        </main>
      </body>
    </html>
  );
}